In [1]:
%load_ext autoreload
%autoreload 2

%matplotlib inline

In [2]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from functools import partial

In [4]:
import tensorflow as tf
import bayesflow as bf

from bayesflow.simulation import TwoLevelPrior, Simulator, TwoLevelGenerativeModel

In [16]:
from simulations import motion_simulation

from priors import hyperprior, partial_pooling_prior

### Priors

In [17]:
hp = hyperprior()

cp = partial_pooling_prior(hp)
print(cp)

[[0.26672792]
 [0.4212296 ]
 [0.08860958]
 [0.43914992]
 [0.03875182]
 [0.87109095]
 [0.28194758]
 [0.2678501 ]
 [0.21025921]
 [0.8769641 ]
 [0.26688305]
 [0.23276968]
 [2.4888427 ]
 [0.7952821 ]]


In [31]:
cp = np.broadcast_to(cp, shape=(14, 1000))
cp

array([[0.26672792, 0.26672792, 0.26672792, ..., 0.26672792, 0.26672792,
        0.26672792],
       [0.4212296 , 0.4212296 , 0.4212296 , ..., 0.4212296 , 0.4212296 ,
        0.4212296 ],
       [0.08860958, 0.08860958, 0.08860958, ..., 0.08860958, 0.08860958,
        0.08860958],
       ...,
       [0.23276968, 0.23276968, 0.23276968, ..., 0.23276968, 0.23276968,
        0.23276968],
       [2.4888427 , 2.4888427 , 2.4888427 , ..., 2.4888427 , 2.4888427 ,
        2.4888427 ],
       [0.7952821 , 0.7952821 , 0.7952821 , ..., 0.7952821 , 0.7952821 ,
        0.7952821 ]], dtype=float32)

In [19]:
prior = TwoLevelPrior(
    hyper_prior_fun=hyperprior, local_prior_fun=partial_pooling_prior
)

prior_sim = prior(batch_size=2)

In [25]:
prior_sim

{'hyper_parameters': array([[2.0360334, 4.1073613],
        [1.4970682, 1.9025397]], dtype=float32),
 'local_parameters': array([[[0.4439463 ],
         [0.52344114],
         [0.39286813],
         [0.34129867],
         [0.16328123],
         [0.16817789],
         [0.31374916],
         [0.22664496],
         [0.14051908],
         [0.51978993],
         [0.45400244],
         [0.1358099 ],
         [2.7438633 ],
         [0.4552013 ]],
 
        [[0.32083222],
         [0.42817718],
         [0.5055262 ],
         [0.05203931],
         [0.57843053],
         [0.37952772],
         [0.6916801 ],
         [0.43617317],
         [0.24263586],
         [0.88701415],
         [0.5365249 ],
         [0.28120878],
         [3.2451754 ],
         [1.5670679 ]]], dtype=float32),
 'batchable_context': None,
 'non_batchable_context': None}

In [27]:
params = prior_sim["local_parameters"]

In [33]:
weight = 0.4
weights = np.array([weight])
weights = np.broadcast_to(weights, shape=(14, 1))
weights

array([[0.4],
       [0.4],
       [0.4],
       [0.4],
       [0.4],
       [0.4],
       [0.4],
       [0.4],
       [0.4],
       [0.4],
       [0.4],
       [0.4],
       [0.4],
       [0.4]])