# Togetherflow
**Emergent agent motion dynamics in immersive rooms**

In this notebook, we implement Togetherflow, a computational cognitive model that characterizes the motion pattern of human agents in immersive rooms.

In [20]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [21]:
%matplotlib inline

In [22]:
import numpy as np
import matplotlib.pyplot as plt
# from functools import partial

np.set_printoptions(suppress=True)

In [23]:
import tensorflow as tf
import bayesflow as bf
from bayesflow.simulation import Prior, Simulator, GenerativeModel

In [45]:
from initializations import (
    initialize_agents, 
    initialize_beacons
)
from influences import (
    position_influence,
    rotation_influence,
    alignment_influence,
    cohesion_influence
)
from simulations import (
    look_at_beacon,
    move_to_beacon
)
from diagnostics import plot_rotation_influence

## Initializations

In [25]:
agent_positions, agent_rotations = initialize_agents()
beacon_positions = initialize_beacons()

## Influences

### 1. Positional influence (individual)

In [26]:
a = agent_positions[0]
a

array([-3.5330856 ,  0.52699804], dtype=float32)

In [27]:
b = beacon_positions[1]
b

array([3.7892935, 4.5694785], dtype=float32)

In [28]:
d = position_influence(agent_positions[0], beacon_positions[1])
d

array([0.8744937 , 0.48503688], dtype=float32)

In [46]:
positions = move_to_beacon(agent_positions[0], beacon_positions[1])
positions

array([[-3.5330856 ,  0.52699804],
       [-3.489405  ,  0.55132914],
       [-3.4456723 ,  0.5755665 ],
       ...,
       [ 3.775882  ,  4.5642705 ],
       [ 3.822511  ,  4.582319  ],
       [ 3.775962  ,  4.564065  ]], dtype=float32)

### 2. Rotational influence (individual)

In [49]:
direction = rotation_influence(
    agent_positions[0], agent_rotations[0], beacon_positions[1],
)
direction

1.3914412260055542

In [50]:
num_agents = len(agent_positions)
e = np.empty((num_agents, 2))
for i in range(num_agents):
    influence = rotation_influence(
        agent_positions[i], agent_rotations[i], 
        beacon_positions[0]
    )
    e[i, 0] = np.cos(influence)
    e[i, 1] = np.sin(influence)

e

array([[ 0.4969887 , -0.86775701],
       [ 0.92379263,  0.38289316],
       [-0.62760785, -0.77852963],
       [-0.70075539, -0.71340163],
       [ 0.11962873,  0.9928187 ],
       [-0.99948238,  0.03217109],
       [-0.63345323,  0.77378098],
       [ 0.72803942, -0.68553527],
       [-0.74905375,  0.66250923],
       [-0.07583761,  0.99712018],
       [ 0.46086734, -0.88746904],
       [ 0.20529991,  0.97869911]])

In [53]:
rotations = look_at_beacon(
    agent_rotation=agent_rotations[0],
    beacon_influence=beacon_positions[1],
    drift_rate=np.pi * 0.1,
    noise=0.05,
    timesteps=1000
)

f, ax = plt.subplots(1, 1, figsize=(16, 4))
ax = plt.plot(np.linspace(0, 1, 101), rotations)

TypeError: some keyword arguments unexpected

In [55]:
type(agent_positions[0, 0])
type(beacon_positions[0, 0])

numpy.float32

In [65]:
positions = move_to_beacon(
    agent_position=agent_positions[0],
    beacon_position=beacon_positions[0]
)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 2d, C) and array(float64, 1d, C) for 'positions.2', defined at C:\Users\Gerald Wong\Documents\Native\Permanent\TogetherFlow\notebooks\togetherflow\simulations.py (173)

File "simulations.py", line 173:
def move_to_beacon(
    <source elided>

        noise = noise_amplitude * (np.random.random(size=2) - 0.5)
        ^

During: typing of assignment at C:\Users\Gerald Wong\Documents\Native\Permanent\TogetherFlow\notebooks\togetherflow\simulations.py (173)

File "simulations.py", line 173:
def move_to_beacon(
    <source elided>

        noise = noise_amplitude * (np.random.random(size=2) - 0.5)
        ^
